### ISSUE TITLE
Don't look at coercions

### ISSUE THREAD

**Issue by Lysxia** [nomeata/inspection-testing#10]
It seems inspection-testing is currently comparing coercions, so that `f` and `g` below are not considered equal. Is it possible to ignore coercions? For a more concrete test case, I'm trying to make [a test  pass in generic-recursion-schemes](https://github.com/Lysxia/generic-recursion-schemes/blob/inspection/test/list.hs), and a coercion seems to be the only remaining difference.

```haskell
{-# LANGUAGE TemplateHaskell #-}
{-# OPTIONS_GHC -fplugin Test.Inspection.Plugin -O #-}

module A where

import Data.Coerce
import Data.Functor.Identity
import Test.Inspection

f :: Int -> Int
f a = a

g :: Int -> Int
g = coerce (\a -> a :: Identity Int)

inspect $ 'f === 'g
```

**Comment by nomeata** [comment]
That’s what `==-` is for!

**Comment by Lysxia** [comment]
Thanks! How could I miss that!?
