### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by isovector** [nomeata/inspection-testing#11]
The "LANGAUGE" means this documentation fails to compile when copy and pasted :)

https://github.com/nomeata/inspection-testing/blob/310c5fad85cc6db396e0b7c9010cb6ad4d4ec4c6/Test/Inspection.hs#L43

**Comment by ulysses4ever** [comment]
Submitted a PR #12 for this.

**Comment by nomeata** [comment]
You don’t want to know how much I write about langauges in my papers… The left pinky is just too fast with the “a”, while the right index finger is slow to stretch…

**Comment by nomeata** [comment]
Fixed in a8b0751
