### ISSUE TITLE
Ignore ordering in mutually recursive blocks

### ISSUE THREAD

**Issue by LightAndLight** [nomeata/inspection-testing#18]
Currently, this example will fail.

```
inf = go0
  where
    go0 = 'a' : go1
    go1 = 'b' : go2
    go2 = 'c' : go0
inf' = go0
  where
    go1 = 'b' : go2
    go0 = 'a' : go1
    go2 = 'c' : go0

 inspect $ 'inf === 'inf'
```

but it doesn't seem like it should.

**Comment by isovector** [comment]
I think I just ran into this. The test [here](https://github.com/isovector/polysemy/commit/a0fbf280ce7ce65f4de1b408742940387e02bcf7#diff-6299865ae11b9b09cdea5c761b913233) fails, even though diffing the outputted broken core is identical for each bind.
