### ISSUE TITLE
GHC 8.6.3 compiles files with -fplugin=Test.Inspection.Plugin twice

### ISSUE THREAD

**Issue by arybczak** [nomeata/inspection-testing#28]
It shows `[Plugin forced recompilation]`. Earlier versions (i.e. 8.4.4, 8.2.2, 8.0.2) compile once.

Is that an issue with inspection-testing or something changed in GHC that warrants it?

**Comment by nomeata** [comment]
Probably related to https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0022-plugin-recompilation.rst and https://ghc.haskell.org/trac/ghc/ticket/7414. Presumably, some CPP code could be added to the plugin that pulls the right switches to prevent the recompilation.
