### ISSUE TITLE
Version 0.4.2 breaks some tests

### ISSUE THREAD

**Issue by nobrakal** [nomeata/inspection-testing#35]
Hi,

### Description
With the recent [0.4.2 release](http://hackage.haskell.org/package/inspection-testing-0.4.2), the test suite of [alga](https://github.com/snowleopard/alga) is broken.

Particularly, one test fails, and it seems it should not (from `alga/test/Algebra/Graph/Test/RewriteRules.hs:42` of the previously mentioned repository):

```
empty1, emptyR :: Graph a
empty1 = transpose Empty
emptyR = Empty

inspect $ 'empty1 === 'emptyR
```

with the following output:

```
alga/test/Algebra/Graph/Test/RewriteRules.hs:42:1: empty1 === emptyR failed:
    LHS:                           
        empty1 :: forall a. Graph a
        [LclIdX,                   
         Unf=Unf{Src=InlineStable, TopLvl=True, Value=True, ConLike=True,
                 WorkFree=True, Expandable=True,
                 Guidance=ALWAYS_IF(arity=0,unsat_ok=True,boring_ok=True)
                 Tmpl= Empty}]     
        empty1 = Empty             
                                   
    RHS:                           
        emptyR :: forall a. Graph a
        [LclIdX,                   
         Unf=Unf{Src=InlineStable, TopLvl=True, Value=True, ConLike=True,
                 WorkFree=True, Expandable=True,
                 Guidance=ALWAYS_IF(arity=0,unsat_ok=True,boring_ok=True)
                 Tmpl= Empty}]     
        emptyR = Empty
```

### How to reproduce
Clone `https://github.com/snowleopard/alga.git`, force the use of `inspection-testing-0.4.2` in `algebraic-graphs.cabal` (which was disabled due to this bug), and run `cabal test` (in fact, I made my tests using stack, but I don't think it changes anything).

### Notes

Theses tests compiled correctly with version `0.4.1.2`.

**Comment by nomeata** [comment]
Thanks, fix uploaded as 0.4.2.1.
