### ISSUE TITLE
Report the type class names on which the test failed

### ISSUE THREAD

**Issue by harendra-kumar** [nomeata/inspection-testing#39]
I am using something like this:

```
inspect $ hasNoTypeClassesExcept 'fromStreamVar [''Exception]
```

The test fails and dumps the core output. However, the core output is long and it is hard figure out which typeclass it failed on. Is it possible to print the name of the type class on which it failed?

**Comment by harendra-kumar** [comment]
Printing just one name would be good enough rather than printing all of them.

**Comment by nomeata** [comment]
It’s a reasonable request! Not sureif I’ll find time to work on it soon… but thanks for the suggestion.
