### ISSUE TITLE
Inspection testing DerivingVia for Semigroups

### ISSUE THREAD

**Issue by Lysxia** [nomeata/inspection-testing#44]
I am trying to add some inspection tests to my generic-data library. In the following snippet, I want to make sure that `x <> (y <> z)` gets simplified as expected with my generic implementation. (I also tried `x <> y` but I ran into more trouble that making the example less trivial seems to avoid.)

https://github.com/Lysxia/generic-data/blob/eaf89511a83c1a9dd9ccb04240be3de5cd606df9/test/inspection.hs

The above test passes on GHC 8.6, but only after manually inlining the code that would result from `DerivingVia`. Instead, if I uncomment the `deriving ... via` clause (and comment the `instance`), I get the following failure. The only difference is that the RHS is defined by coercing an intermediate binding that is pretty much equal to the LHS with an extra coercion.

Shouldn't these be considered the same?

```
inspection.hs:54:1: mappendT === mappendTG failed:
    LHS:    
        mappendT
        mappendT
          = \ w_sczi w_sczj w_sczk ->
              case w_sczi of { T ww_sczn ww_sczo ->
              case w_sczj of { T ww_sczs ww_sczt ->
              case w_sczk of { T ww_sczx ww_sczy ->
              T (case ww_sczn of { I# x ->
                 case ww_sczs of { I# x ->
                 case ww_sczx of { I# y -> I# (+# x (+# x y)) }
                 }
                 })
                (case ww_sczo of {
                   False -> False;
                   True -> && ww_sczt ww_sczy
                 })
              }
              }
              }
            
    RHS:    
        mappendTG
        mappendTG = mappendTG_schU `cast` <Co:13>
            
        mappendTG_schU
        mappendTG_schU
          = \ w_scyW w_scyX w_scyY ->
              case w_scyW of { T ww_scz1 ww_scz2 ->
              case w_scyX of { T ww_scz6 ww_scz7 ->
              case w_scyY of { T ww_sczb ww_sczc ->
              (T (case ww_scz1 of { I# x ->
                  case ww_scz6 of { I# x ->
                  case ww_sczb of { I# y -> I# (+# x (+# x y)) }
                  }
                  })
                 (case ww_scz2 of {
                    False -> False;
                    True -> && ww_scz7 ww_sczc
                  }))
              `cast` <Co:8>
              }
              }
              }
 ```

**Comment by nomeata** [comment]
You need to use [`==-`](http://hackage.haskell.org/package/inspection-testing-0.4.2.2/docs/Test-Inspection.html#v:-61--61--45-) if you want to ignore differences in type level features.

**Comment by Lysxia** [comment]
Oh, great, thanks!
