### ISSUE TITLE
`(==-)` should ignore coverage-related core functions

### ISSUE THREAD

**Issue by konn** [nomeata/inspection-testing#47]
When built with `-fhpc` ghc flag or `--coverage` stack option, core representation can be different than those without coverage options.

Consider the following:

```haskell
{-# OPTIONS_GHC -fhpc -O2 #-}
{-# LANGUAGE TemplateHaskell #-}
module Main where
import Test.Inspection

theTwo :: Int
theTwo = 2

theOnePlusOne :: Int
theOnePlusOne = 1 + 1

anotherTwo :: Int
anotherTwo = 2

inspect $ 'theTwo ==- 'theOnePlusOne
inspect $ 'theTwo ==- 'anotherTwo

main :: IO ()
main = print theOnePlusOne
```

Without `-fhpc` option, this compiles successfully; but with `-fhpc` option, we will get the following compilation error:

```
[1 of 1] Compiling Main
/Users/hiromi/Documents/Programming/Haskell/git/coverage-and-inspection/src/Main.hs:15:1: theTwo ==- theOnePlusOne failed:
    LHS:
        theTwo :: Int
        [LclIdX,
         Unf=Unf{Src=<vanilla>, TopLvl=True, Value=False, ConLike=False,
                 WorkFree=False, Expandable=False, Guidance=IF_ARGS [] 10 20}]
        theTwo = hpc<Main,10> hpc<Main,9> I# 2#
        
    RHS:
        theOnePlusOne :: Int
        [LclIdX,
         Unf=Unf{Src=<vanilla>, TopLvl=True, Value=False, ConLike=False,
                 WorkFree=False, Expandable=False, Guidance=IF_ARGS [] 10 20}]
        theOnePlusOne
          = hpc<Main,8> hpc<Main,7> hpc<Main,5> hpc<Main,6> I# 2#
        
/Users/hiromi/Documents/Programming/Haskell/git/coverage-and-inspection/src/Main.hs:16:1: theTwo ==- anotherTwo failed:
    LHS:
        theTwo :: Int
        [LclIdX,
         Unf=Unf{Src=<vanilla>, TopLvl=True, Value=False, ConLike=False,
                 WorkFree=False, Expandable=False, Guidance=IF_ARGS [] 10 20}]
        theTwo = hpc<Main,10> hpc<Main,9> I# 2#
        
    RHS:
        anotherTwo :: Int
        [LclIdX,
         Unf=Unf{Src=<vanilla>, TopLvl=True, Value=False, ConLike=False,
                 WorkFree=False, Expandable=False, Guidance=IF_ARGS [] 10 20}]
        anotherTwo = hpc<Main,4> hpc<Main,3> I# 2#
        

src/Main.hs: error:
    inspection testing unsuccessful
         unexpected failures: 2
```

If all the tested functionalities are provided in the single module and no other tests are taken place, just adding `-fno-hpc` GHC option would suffice.
But, in general, there can be non-inspection tests for the same functionalities, or worse, the functions are scattered across multiple libraries.
In such a situation, if one wants to get the coverage report for them, one has to compile the library with `-fhpc` flag.
Then, the closures of form `hpc` still remain in the Core.
This means that one has to build libraries twice (once with `-fhpc` and then `-fno-hpc`) and separate test programs to control the timing of inspection tests.

It might be good to ignore `hpc` in `(==-)`, as coercions and type lambdas are already ignored.

**Comment by nomeata** [comment]
Fully agree, patch welcome :-)

**Comment by konn** [comment]
Oh, it seems much easier to fix this than I expected! I will pull-request shortly.
