### ISSUE TITLE
tasty integration

### ISSUE THREAD

**Issue by Bodigrim** [nomeata/inspection-testing#56]
Is there an existing package for `tasty` integration? I did not find any, so sketched https://github.com/Bodigrim/tasty-inspection-testing, but I suspect that I'm reinventing a wheel.

**Comment by phadej** [comment]
In `optics` we reinvent the wheel. We found that `assertFailure` is important too, i.e. we have

```
assertSuccess :: Result -> IO ()
assertSuccess (Success _)   = return ()
assertSuccess (Failure err) = assertFailure err

assertFailure' :: Result -> IO ()
assertFailure' (Success err) = assertFailure err
assertFailure' (Failure _)   = return ()
```

(tick to avoid clash with `tasty-hunit` `assertFailure`)....

but more importantly we have also

```
ghc82to86failure :: Result -> IO ()
#if __GLASGOW_HASKELL__ >= 802 && __GLASGOW_HASKELL__ <= 806
ghc82to86failure = assertFailure'
#else
ghc82to86failure = assertSuccess
#endif
```

etc. as GHC changes, and sometimes it's very much fine to just accept things don't work perfectly on some GHC version. See https://github.com/well-typed/optics/blob/master/optics/tests/Optics/Tests/Utils.hs

**Comment by Bodigrim** [comment]
Yeah, I looked at several other packages, and they wrap `inspection-testing` into `tasty-hunit` as well. What I do not quite enjoy is an additional level of verbosity:

```haskell
testGroup "Eta expansion"
  [ testCase "toListOf folded = \\s -> toListOf folded s" $
    assertSuccess $(inspectTest $ 'eta1lhs === 'eta1rhs)
  , testCase "optimized eta1lhs" $
    assertSuccess $(inspectTest $ hasNoProfunctors 'eta1lhs) ...
```

`inspection-testing` allows to name an `Obligation` and is pretty good at autogenerating names as well, so it would be nice to reuse it as a test name. Ideally I would like to write just 

```haskell
testGroup "Eta expansion" 
  [ $(inspectTest $ 'eta1lhs === 'eta1rhs)
  , $(inspectTest $ hasNoProfunctors 'eta1lhs) ...
  ]
```

I implemented the latter approach at https://github.com/Bodigrim/tasty-inspection-testing, but unfortunately had to copy and modify a significant portion of `inspection-testing`. It would be insteresting to discuss how to reuse more, but it is probably quite challenging. Otherwise this issue can be closed.

**Comment by nomeata** [comment]
I think I should avoid depending on `tasty` in this library, but if `inspection-testig` should export more, or have an `.Internals` module, PRs are welcome!

**Comment by Bodigrim** [comment]
@nomeata would it be possible to expose `checkProperty` and `CheckResult` from `Test.Inspection.Plugin`?

**Comment by nomeata** [comment]
Sure!

**Comment by Bodigrim** [comment]
Thanks for a quick turnaround, @nomeata! 
With the latest changes, https://github.com/Bodigrim/tasty-inspection-testing allows to reduce boilerplate in `tasty` test suites as follows: https://github.com/Bodigrim/optics/commit/5af0106ef0364b2d181160297a2c093bda0f670f (using `optics` tests as a guinea pig).
