### ISSUE TITLE
Checking for rewrite rules to trigger?

### ISSUE THREAD

**Issue by ChShersh** [nomeata/inspection-testing#6]
I came across this tool. And I wonder: is it possible to check whether my Rewrite Rule triggered with `inspection-testing` or not? This would be really useful! If so, it would be really nice to have some simple example that shows such feature.

**Comment by nomeata** [comment]
That is not really within the scope of this tool. But you can simply run ghc with `-ddump-rule-firings` and check the output (and you can automate that in a script).

Alternatively, you _can_ use `inspection-testing` to check for properties of the rewritten code, e.g. the absence of some data structure. https://github.com/nomeata/inspection-testing/blob/master/examples/Fusion.hs is an example for that.

**Comment by ChShersh** [comment]
@nomeata Thanks! That's really useful :)

**Comment by nomeata** [comment]
Glad to be of service.
