### ISSUE TITLE
Integration with normal testing frameworks

### ISSUE THREAD

**Issue by mpickering** [nomeata/inspection-testing#7]
It is hard to use `inspection-testing` with normal test frameworks as it just errors if one of the tests fails. There's no sensible way to integrate it into a `tasty` or `hspec` test suite for example.

Instead of aborting the compilation could the compiler not synthesise a test report? At it's simplest it could just replace `inspect ...` with `True` or `False` to indicate the result of the test which a framework could then interpret it its own way.

**Comment by nomeata** [comment]
That’s a good idea, and should be no problem at all. It could even synthesize something more helpful, e.g. with an error message, and something that fails helpfully if the plugin did not actually run.

**Comment by mpickering** [comment]
Do you intend to implement this or are you soliciting volunteers?

**Comment by nomeata** [comment]
I’d implement it eventually, I think, but if you want to see it sooner, then patches are welcome.

I guess I am hesitant about the interface. If it is a boolean value, then the `inspect` top-level spice no longer feels like the right interface. So instead of
```
inspect $ 'foo === 'bar
```
you want something like
```
test1 = $(inspect' $ 'foo === 'bar)
```
maybe? Is there a good name for the expression-variant of `inspect`?

It might make sense to provide this in a separate module.

**Comment by nomeata** [comment]
I looked into it a bit right now, and I am not sure how to do the plumbing. From a user point of view, we really want
```
tests = [ $(inspect' $ 'foo === 'bar)
        , $(inspect' $ 'bar == 'baz)
        ]
```

**Comment by nomeata** [comment]
I have something that will probably work, but I am stuck at synthesizing core expressions in a GHC plugin, see https://mail.haskell.org/pipermail/glasgow-haskell-users/2018-January/026685.html

Help is appreciated.

**Comment by nomeata** [comment]
Nevermind, I think I found a way.

**Comment by nomeata** [comment]
Ok, I have something that seems to work. @mpickering, can you play around with it and see if it does what you need before I cut a release?

**Comment by mpickering** [comment]
Can you not use `addTopDecls` to add new top level declarations whilst splicing into an expression?

**Comment by nomeata** [comment]
Ha, precisely what I need! I must have missed that.

**Comment by mpickering** [comment]
@nomeata I'm working on a PR currently.

**Comment by nomeata** [comment]
oh, me too :)

**Comment by nomeata** [comment]
I pushed mine, but I am willing to hear if you would have done it differently :-)

**Comment by mpickering** [comment]
Thanks looks like my patch but I think you can delete all the `FindAgain` stuff now? Also the test isn't compiled by the test suite yet, not sure if you intended that.

**Comment by nomeata** [comment]
>  I think you can delete all the FindAgain stuff now? 

No, unfortunately not. I get weird
```
<interactive>:1:1: error:
    The exact Name ‘inspect_23_9_alEA’ is not in scope
      Probable cause: you used a unique Template Haskell name (NameU), 
      perhaps via newName, but did not bind it
      If that's it, then -ddump-splices might be useful
```
errors when I try to store the `TH.Name` instead of the string in `storeResult`. But if you can get it to work, then that’d be great!

**Comment by mpickering** [comment]
I don't think you need the `storeResult` field either?

**Comment by mpickering** [comment]
Ah perhaps that is wrong. Anyway, this works great for me now. Thanks for implementing it.

**Comment by nomeata** [comment]
I guess I could do without the `storeResult` if I used the convention that an obligation attached to the module is a compile-time one, and one attached to a top-level definition means that that definition ought to be overriden with that result… I guess that’s cleaner.

**Comment by nomeata** [comment]
Yes, I can do without: b2811aa

> Anyway, this works great for me now. 

Did you test it already? everything fine and releasable?

**Comment by mpickering** [comment]
Yes I integrated it and it works as expected. Doing a release would be great.

**Comment by nomeata** [comment]
Uploaded as version 0.2
