### ISSUE TITLE
Test Suite Failures

### ISSUE THREAD

**Issue by dwincort** [nomeata/inspection-testing#9]
Are the tests supposed to fail when I run them?  The core output of, e.g., `roundtrip` and `roundtrip_id` in `NS_NP` are indeed different, so I understand that the test `inspect $ 'roundtrip === 'roundtrip_id` would fail -- I'm just not sure why failing tests are part of the test suite.  Or, is there something going on on my end?  Should the core of those two be the same?

For some context, I'm working in a group where we like to have all of our dependencies' test suites pass.  I can put in overrides, but that's a little concerning---I like to know that the packages I'm using at least pass their writers' tests.

**Comment by nomeata** [comment]
The tests pass on travis: https://travis-ci.org/nomeata/inspection-testing/jobs/336425171
```
[1 of 1] Compiling NS_NP            ( examples/NS_NP.hs, /tmp/dist-test.vHPX/dist-newstyle/build/x86_64-linux/ghc-8.2.2/inspection-testing-0.2.0.1/t/NS_NP/build/NS_NP/NS_NP-tmp/NS_NP.o )
examples/NS_NP.hs:44:1: roundtrip === roundtrip_id passed.
inspection testing successful
      expected successes: 1
```

So it seems to be something on your end. Do you override some GHC options?

**Comment by dwincort** [comment]
Hmm.  We do turn on profiling libs by default.  I'll check with my group to see if there's anything else.

Thanks for confirming that it's on our end.  I won't bug you about it anymore :).

**Comment by nomeata** [comment]
Oh, I expect profiling to get in the way of testing. Maybe `inspection-testing` should simply not do anything if it detects that profiling is on.

**Comment by shlevy** [comment]
I think the issue may be that we build *exes* with profiling, not just libs. Let me verify.
